# Test gradient masking WITHOUT sharpening to isolate the issue
model:
  checkpoint_path: 'checkpoints/checkpoint.pt'
  image_size: 128
  num_channels: 128
  num_res_blocks: 2
  num_heads: 4
  num_head_channels: 64
  attention_resolutions: '32,16,8'
  use_fp16: true
  learn_sigma: true

quality:
  preset: 'fast'  # Use fast preset for quicker testing
  face_hide_percentage: 0.5  # Standard 50% face hiding
  use_gradient_mask: true   # ENABLED - Linear gradient masking
  blur_kernel_size: 15      # Moderate transition width
  sharpening_strength: 0.0  # DISABLED - No sharpening to isolate gradient effect
  
processing:
  batch_size: 2  # Small batch for testing
  use_ddim: true
  face_det_batch_size: 16  # Smaller batch for testing
  pads: [0, 0, 0, 0]
  video_fps: 25
  sample_rate: 16000
  syncnet_mel_step_size: 16

audio:
  enhanced_processing: false
  num_mels: 80
  n_fft: 800
  hop_size: 200

optimization:
  enable_cuda_optimizations: true
  torch_compile: false  # Disable to avoid Triton issues during testing
  memory_cleanup_interval: 2
  gpu_memory_monitoring: true

paths:
  input_video: 'test_media/person_short.mp4'
  input_audio: 'test_media/speech.m4a'
  output_video: 'output_dir/test_linear_gradient_only.mp4'
  temp_dir: 'temp'
