# Phase 2.1 Test: 256x256 Resolution Enhancement
model:
  checkpoint_path: 'checkpoints/checkpoint.pt'
  image_size: 256                    # Phase 2.1 - Doubled resolution (4x more detail)
  num_channels: 256                  # Phase 2.1 - Increased model capacity
  num_res_blocks: 2
  num_heads: 4
  num_head_channels: 64
  attention_resolutions: '64,32,16,8' # Phase 2.1 - Extended for higher resolution
  use_fp16: true
  learn_sigma: true

quality:
  preset: 'high'                     # High quality preset (ddim50)
  face_hide_percentage: 0.5    
  use_gradient_mask: false           # Hard masking (proven superior)
  blur_kernel_size: 15         
  sharpening_strength: 0.3           # Phase 1.3 - Moderate sharpening
  
processing:
  batch_size: 2                      # Phase 2.1 - Reduced for 256x256 memory requirements
  use_ddim: true
  face_det_batch_size: 32           # Phase 2.1 - Reduced for higher resolution
  pads: [0, 0, 0, 0]
  video_fps: 25
  sample_rate: 16000
  syncnet_mel_step_size: 16

audio:
  enhanced_processing: false
  num_mels: 80
  n_fft: 800
  hop_size: 200

optimization:
  enable_cuda_optimizations: true
  torch_compile: false              # Phase 2.1 - Disabled for stability
  memory_cleanup_interval: 2        # Phase 2.1 - More frequent cleanup
  gpu_memory_monitoring: true

paths:
  input_video: 'test_media/person_short.mp4'
  input_audio: 'test_media/speech.m4a'
  output_video: 'output_dir/phase2_1_256_resolution.mp4'
  temp_dir: 'temp'
